### ISSUE TITLE
【bug】自动体力查询和推送报错

### ISSUE THREAD

**Issue by mengluo04** [baiqwerdvd/StarRailUID#23]
```bash
08-09 11:30:00 [DEBUG] gsuid_core.utils.api.mys.base_request | {'x-rpc-app_version': '2.71.1', 'X-Requested-With': 'com.mihoyo.hyperion', 'User-Agent': 'Mozilla/5.0 (Linux; Android 13; TEL-AN00a HONORTEL-AN00a; wv)AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97Mobile Safari/537.36 miHoYoBBS/22.71.1', 'x-rpc-client_type': '5', 'Referer': 'https://webstatic.mihoyo.com/', 'Origin': 'https://webstatic.mihoyo.com/', 'DS': '1723174200,144356,9d5a8df627663eea3568cc7a27310bd3', 'Cookie': 'account_id=283142557;cookie_token=Is9QnKLx6hLf6znDmu1X8eRsvZWS2yC9NmG7eH2K', 'x-rpc-device_fp': '38d7ee6003836', 'x-rpc-device_id': '6b26d376-0384-4648-9ab3-c54e0d8f2165'} 
08-09 11:30:00 [DEBUG] gsuid_core.utils.api.mys.base_request | {'x-rpc-app_version': '2.71.1', 'X-Requested-With': 'com.mihoyo.hyperion', 'User-Agent': 'Mozilla/5.0 (Linux; Android 13; TEL-AN00a HONORTEL-AN00a; wv)AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97Mobile Safari/537.36 miHoYoBBS/22.71.1', 'x-rpc-client_type': '5', 'Referer': 'https://webstatic.mihoyo.com/', 'Origin': 'https://webstatic.mihoyo.com/', 'DS': '1723174200,195164,b555fdc7d83b0df02783531c77e0019c', 'Cookie': 'account_id=283142557;cookie_token=Is9QnKLx6hLf6znDmu1X8eRsvZWS2yC9NmG7eH2K', 'x-rpc-device_fp': '38d7ee6003836', 'x-rpc-device_id': '6b26d376-0384-4648-9ab3-c54e0d8f2165'} 
08-09 11:30:00 [DEBUG] gsuid_core.utils.api.mys.base_request | {'retcode': 0, 'message': 'OK', 'data': {'current_resin': 113, 'max_resin': 200, 'resin_recovery_time': '41617', 'finished_task_num': 0, 'total_task_num': 4, 'is_extra_task_reward_received': False, 'remain_resin_discount_num': 3, 'resin_discount_num_limit': 3, 'current_expedition_num': 5, 'max_expedition_num': 5, 'expeditions': [{'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u705lg/88c712d29e7d09f80ecccace40a579ce.png', 'status': 'Finished', 'remained_time': '0'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u705lg/79afc3ffdf5daa9dc5b84f3a2197e673.png', 'status': 'Finished', 'remained_time': '0'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u705lg/649e11627c4519f630bff1ad6ee31b77.png', 'status': 'Finished', 'remained_time': '0'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u705lg/a9b45a05cedff67bbc3662f7d902a029.png', 'status': 'Finished', 'remained_time': '0'}, {'avatar_side_icon': 'https://act-webstatic.mihoyo.com/hk4e/e20200928calculate/item_avatar_side_icon_u705lg/8d27f84fa150de571d9122833a2e690f.png', 'status': 'Finished', 'remained_time': '0'}], 'current_home_coin': 2400, 'max_home_coin': 2400, 'home_coin_recovery_time': '0', 'calendar_url': '', 'transformer': {'obtained': True, 'recovery_time': {'Day': 1, 'Hour': 0, 'Minute': 0, 'Second': 0, 'reached': False}, 'wiki': 'https://bbs.mihoyo.com/ys/obc/content/1562/detail?bbs_presentation_style=no_header', 'noticed': False, 'latest_job_id': '0'}, 'daily_task': {'total_num': 4, 'finished_num': 0, 'is_extra_task_reward_received': False, 'task_rewards': [{'status': 'TaskRewardStatusUnfinished'}, {'status': 'TaskRewardStatusUnfinished'}, {'status': 'TaskRewardStatusUnfinished'}, {'status': 'TaskRewardStatusUnfinished'}], 'attendance_rewards': [{'status': 'AttendanceRewardStatusUnfinished', 'progress': 0}, {'status': 'AttendanceRewardStatusUnfinished', 'progress': 0}, {'status': 'AttendanceRewardStatusUnfinished', 'progress': 0}, {'status': 'AttendanceRewardStatusUnfinished', 'progress': 0}], 'attendance_visible': True, 'stored_attendance': '69.6', 'stored_attendance_refresh_countdown': 1625400}, 'archon_quest_progress': {'list': [], 'is_open_archon_quest': True, 'is_finish_all_mainline': True, 'is_finish_all_interchapter': True, 'wiki_url': ''}}} 
08-09 11:30:00 [DEBUG] gsuid_core.utils.api.mys.base_request | {'retcode': 0, 'message': 'OK', 'data': {'current_stamina': 64, 'max_stamina': 240, 'stamina_recover_time': 63132, 'accepted_epedition_num': 4, 'total_expedition_num': 4, 'expeditions': [{'avatars': ['https://act-webstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_ud09dc/5e40e15856bb5cf0e125c2de15ca63d8.png', 'https://act-webstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_ud09dc/50858e997abc7b29f475dcd1960b1dea.png'], 'status': 'Ongoing', 'remaining_time': 13745, 'name': '离垢清净', 'item_url': 'https://act-webstatic.mihoyo.com/game_record/hkrpg/SpriteOutput/ItemIcon/114011.png'}, {'avatars': ['https://act-webstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_ud09dc/6bc93cc3f590b1baf8b01ff0d1f0d896.png', 'https://act-webstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_ud09dc/4494a2cbaed942e6c76e8debb50beace.png'], 'status': 'Ongoing', 'remaining_time': 13745, 'name': '无名之地，无名之人', 'item_url': 'https://act-webstatic.mihoyo.com/game_record/hkrpg/SpriteOutput/ItemIcon/211.png'}, {'avatars': ['https://act-webstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_ud09dc/08d54ac4b80ca302547e729383f489c7.png', 'https://act-webstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_ud09dc/4938d3537241d7c92b9958534e20e1e0.png'], 'status': 'Ongoing', 'remaining_time': 13745, 'name': '阿卡夏记录', 'item_url': 'https://act-webstatic.mihoyo.com/game_record/hkrpg/SpriteOutput/ItemIcon/221.png'}, {'avatars': ['https://act-webstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_ud09dc/670d2239f0606bb75349e82c88963a25.png', 'https://act-webstatic.mihoyo.com/darkmatter/hkrpg/prod_gf_cn/item_icon_ud09dc/402db3829c9b099f91983a772f426148.png'], 'status': 'Ongoing', 'remaining_time': 13745, 'name': '赡养人类', 'item_url': 'https://act-webstatic.mihoyo.com/game_record/hkrpg/SpriteOutput/ItemIcon/181012.png'}], 'current_train_score': 100, 'max_train_score': 500, 'current_rogue_score': 12000, 'max_rogue_score': 14000, 'weekly_cocoon_cnt': 3, 'weekly_cocoon_limit': 3, 'current_reserve_stamina': 1, 'is_reserve_stamina_full': False, 'rogue_tourn_weekly_unlocked': True, 'rogue_tourn_weekly_max': 1000, 'rogue_tourn_weekly_cur': 0}} 
Job "sr_notice_job (trigger: cron[minute='*/30'], next run at: 2024-08-09 12:00:00 CST)" raised an exception
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-y7-8B4ky-py3.10/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/software/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_stamina/__init__.py", line 43, in sr_notice_job
    result = await get_notice_list()
  File "/home/software/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_stamina/notice.py", line 29, in get_notice_list
    push_data = await GsPush.select_data_by_uid(user.sr_uid, 'sr')
  File "/home/software/gsuid_core/gsuid_core/utils/database/base_models.py", line 45, in wrapper
    data = await func(self, session, *args, **kwargs)
  File "/home/software/gsuid_core/gsuid_core/utils/database/base_models.py", line 1476, in select_data_by_uid
    getattr(cls, cls.get_gameid_name(game_name)) == uid,
  File "/root/.cache/pypoetry/virtualenvs/gsuid-core-y7-8B4ky-py3.10/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 237, in __getattr__
    raise AttributeError(item)
AttributeError: sr_uid
```

**Comment by mengluo04** [comment]
定位到原因了，gspush里面没有sr_uid的字段，没有做适配
建议使用独立的推送model，

**Comment by baiqwerdvd** [comment]
#33
