### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by QSlotus** [baiqwerdvd/StarRailUID#3]
插件加载失败
```
02-17 09:02:46 [INFO] gsuid_core.server | 安装依赖 starrail-damage-cal 中...
2024-02-17 09:02:46.762 | ERROR    | gsuid_core.server:load_plugins:131 - 加载插件时发生错误: [Errno 2] No such file or directory: 'pdm run pip install starrail-damage-cal'
Traceback (most recent call last):

  File "/data/gsuid_core/gsuid_core/core.py", line 13, in <module>
    from gsuid_core.gss import gss  # noqa: E402

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/data/gsuid_core/gsuid_core/gss.py", line 12, in <module>
    gss.load_plugins()
    │   └ <function GsServer.load_plugins at 0x7f256cc05f30>
    └ <gsuid_core.server.GsServer object at 0x7f256fd33940>

> File "/data/gsuid_core/gsuid_core/server.py", line 101, in load_plugins
    check_pyproject(pyproject)
    │               └ PosixPath('/data/gsuid_core/gsuid_core/plugins/StarRailUID/pyproject.toml')
    └ <function check_pyproject at 0x7f256cc05d80>

  File "/data/gsuid_core/gsuid_core/server.py", line 202, in check_pyproject
    install_dependencies(dependencies)
    │                    └ {'beautifulsoup4': '>=4.12.2', 'msgspec': '>=0.18.4', 'httpx': '>=0.25.0', 'pillow': '>=10.1.0', 'aiofiles': '>=23.2.1', 'aio...
    └ <function install_dependencies at 0x7f256cc06320>

  File "/data/gsuid_core/gsuid_core/server.py", line 230, in install_dependencies
    result = subprocess.run(
             │          └ <function run at 0x7f256fa4dfc0>
             └ <module 'subprocess' from '/usr/lib/python3.10/subprocess.py'>

  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
         │      │            └ {'text': True, 'stdout': -1, 'stderr': -1}
         │      └ ('pdm run pip install starrail-damage-cal',)
         └ <class 'subprocess.Popen'>
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    │    │              │     │           │           └ True
    │    │              │     │           └ None
    │    │              │     └ None
    │    │              └ 'pdm run pip install starrail-damage-cal'
    │    └ <function Popen._execute_child at 0x7f256fa4eef0>
    └ <Popen: returncode: 255 args: 'pdm run pip install starrail-damage-cal'>
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
          │                    │          │        └ 'pdm run pip install starrail-damage-cal'
          │                    │          └ 'No such file or directory'
          │                    └ 2
          └ <class 'OSError'>

FileNotFoundError: [Errno 2] No such file or directory: 'pdm run pip install starrail-damage-cal'
  File "/data/gsuid_core/gsuid_core/server.py", line 101, in load_plugins
    check_pyproject(pyproject)
  File "/data/gsuid_core/gsuid_core/server.py", line 202, in check_pyproject
    install_dependencies(dependencies)
  File "/data/gsuid_core/gsuid_core/server.py", line 230, in install_dependencies
    result = subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
02-17 09:02:46 [WARNING] gsuid_core.server | 插件StarRailUID加载失败
```
pdm版本 2.12.3
python版本 3.10.12
pip版本 22.0.2

**Comment by ishkong** [comment]
自己手动装一下依赖

**Comment by QSlotus** [comment]
具体怎么装呢
我进入了`plugins/StarRailUID`目录
用`pdm install`装了一次，还是报之前的错误
然后我又到插件目录里用 `pdm run pip install starrail-damage-cal` 装了一次，显示安装成功了
![image](https://github.com/baiqwerdvd/StarRailUID/assets/109905194/b14c18d8-13c4-4d8d-9b4b-c63b8cd413d0)
但是还是报上面一样的错误

**Comment by baiqwerdvd** [comment]
`pdm run python -m ensurepip`
然后`pdm run python -m pip install starrail-damage-cal --upgrade`

**Comment by QSlotus** [comment]
已成功，感谢

**Comment by cnxiaodoubi** [comment]
如果是poetry 安装的 咋整
