### ISSUE TITLE
根据#3和#8的Issues试图pdm run pip install starrail-damage-cal后，仍提示ModuleNotFoundError: No module named 'starrail_damage_cal'

### ISSUE THREAD

**Issue by jiang068** [baiqwerdvd/StarRailUID#48]
最开始想给gscore添加StarRailUID时直接给bot发送core安装插件starrail或者core安装插件StarRailUID都没反应，
我就到plugins文件夹下git clone https://github.com/baiqwerdvd/StarRailUID.git --depth=1 --single-branch，
重启后报错ModuleNotFoundError: No module named 'starrail_damage_cal'

查找Issues#3，试图手动安装依赖成功后，
回到core文件夹下，对照Issues#8“在core的目录下执行pdm run python -m pip install starrail-damage-cal --upgrade”，
再poetry run core无法启动。
再次poetry install后poetry run core，可以启动但还是报错ModuleNotFoundError: No module named 'starrail_damage_cal'。

其他插件均正常。
Ubuntu22.04，pip22.0.2，python3.1，poetry1.8.5，pdm2.22.1

**Comment by jiang068** [comment]
附启动时的实时日志：
 12-31 12:11:23 [INFO] plugins.WutheringWavesUID.WutheringWavesUID.wutheringwaves_resource | [鸣潮][资源文件下载] 正在检查与下载缺失的资源文件，可能需要较长时间，请稍等 
 12-31 12:11:23 [SUCCESS] gsuid_core.server | 插件WutheringWavesUID导入成功! 
 2024-12-31 12:11:23.586 | ERROR    | gsuid_core.server:load_plugins:124 - 加载插件时发生错误: No module named 'starrail_damage_cal'
Traceback (most recent call last):

  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'gsuid_core.core'
           │          └ <function _gcd_import at 0x703d78963400>
           └ <module '_frozen_importlib' (frozen)>
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/ubuntu/Desktop/gsuid_core/gsuid_core/core.py", line 15, in <module>
    from gsuid_core.gss import gss  # noqa: E402

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/ubuntu/Desktop/gsuid_core/gsuid_core/gss.py", line 10, in <module>
    gss.load_plugins()
    │   └ <function GsServer.load_plugins at 0x703d74b79b40>
    └ <gsuid_core.server.GsServer object at 0x703d77bc2860>

> File "/home/ubuntu/Desktop/gsuid_core/gsuid_core/server.py", line 94, in load_plugins
    self.load_dir_plugins(path, True)
    │    │                └ PosixPath('/home/ubuntu/Desktop/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID')
    │    └ <function GsServer.load_dir_plugins at 0x703d74b79bd0>
    └ <gsuid_core.server.GsServer object at 0x703d77bc2860>

  File "/home/ubuntu/Desktop/gsuid_core/gsuid_core/server.py", line 147, in load_dir_plugins
    importlib.import_module(f'{_p}')
    │         └ <function import_module at 0x703d788e4ca0>
    └ <module 'importlib' from '/usr/lib/python3.10/importlib/__init__.py'>

  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.StarRailUID.StarRailUID.starrailuid_wiki'
           │          └ <function _gcd_import at 0x703d78963400>
           └ <module '_frozen_importlib' (frozen)>
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "/home/ubuntu/Desktop/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/starrailuid_wiki/__init__.py", line 8, in <module>
    from ..utils.name_covert import (

  File "/home/ubuntu/Desktop/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID/utils/name_covert.py", line 3, in <module>
    from starrail_damage_cal.excel.model import CharAlias

ModuleNotFoundError: No module named 'starrail_damage_cal'
12-31 12:11:23 [WARNING] gsuid_core.server | 插件StarRailUID加载失败 
 12-31 12:11:23 [INFO] uvicorn.server | Started server process [1544] 
 12-31 12:11:23 [INFO] uvicorn.lifespan.on | Waiting for application startup. 
 12-31 12:11:24 [INFO] gsuid_core.webconsole.__init__ | 尝试挂载WebConsole 
 12-31 12:11:24 [WARNING] gsuid_core.webconsole.__init__ | WebConsole挂载于本地

**Comment by Lover-v** [comment]
遇到了相同情况简单说一下我的处理：
1.在gscore目录下运行poetry env info命令，查看环境的地址
2.找到地址目录，cmd运行Scripts/activate，进入到虚拟环境
3.运行python -m pip install starrail-damage-cal 即可。
感觉改pyproject.toml文件然后poetry install应该也可以吧

**Comment by cnxiaodoubi** [comment]
> 遇到了相同情况简单说一下我的处理： 1.在gscore目录下运行poetry env info命令，查看环境的地址 2.找到地址目录，cmd运行Scripts/activate，进入到虚拟环境 3.运行python -m pip install starrail-damage-cal 即可。 感觉改pyproject.toml文件然后poetry install应该也可以吧

你这个方法还是不行我py3.11.10

**Comment by cnxiaodoubi** [comment]
> 遇到了相同情况简单说一下我的处理： 1.在gscore目录下运行poetry env info命令，查看环境的地址 2.找到地址目录，cmd运行Scripts/activate，进入到虚拟环境 3.运行python -m pip install starrail-damage-cal 即可。 感觉改pyproject.toml文件然后poetry install应该也可以吧

你wind跑的吧

**Comment by cnxiaodoubi** [comment]
poetry add starrail_damage_cal  解决了

**Comment by jiang068** [comment]
> poetry add starrail_damage_cal 解决了

已解决，感谢指点！
