### ISSUE TITLE
加载插件时发生错误: No module named 'starrail_damage_cal'

### ISSUE THREAD

**Issue by 54yq** [baiqwerdvd/StarRailUID#8]
已经在gsuid_core\plugins\StarRailUID目录下执行`pdm install`并生成了starrailuid-0.1.0相关文件，但运行时仍有报错无法加载
```
04-21 14:55:19 [INFO] gsuid_core.server | 安装依赖 starrail-damage-cal 中...
04-21 14:55:22 [SUCCESS] gsuid_core.server | 依赖 starrail-damage-cal 安装成功！
2024-04-21 14:55:22.669 | ERROR    | gsuid_core.server:load_plugins:131 - 加载插件时发生错误: No module named 'starrail_damage_cal'
Traceback (most recent call last):

  File "G:\bot\HoshinoBot v2\gsuid_core\gsuid_core\core.py", line 13, in <module>
    from gsuid_core.gss import gss  # noqa: E402

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "G:\bot\HoshinoBot v2\gsuid_core\gsuid_core\gss.py", line 12, in <module>
    gss.load_plugins()
    │   └ <function GsServer.load_plugins at 0x0000016CDD8C5670>
    └ <gsuid_core.server.GsServer object at 0x0000016CDC47E2B0>

> File "G:\bot\HoshinoBot v2\gsuid_core\gsuid_core\server.py", line 103, in load_plugins
    self.load_dir_plugins(path, True)
    │    │                └ WindowsPath('G:/bot/HoshinoBot v2/gsuid_core/gsuid_core/plugins/StarRailUID/StarRailUID')
    │    └ <function GsServer.load_dir_plugins at 0x0000016CDD8C5700>
    └ <gsuid_core.server.GsServer object at 0x0000016CDC47E2B0>

  File "G:\bot\HoshinoBot v2\gsuid_core\gsuid_core\server.py", line 147, in load_dir_plugins
    importlib.import_module(f'{_p}')
    │         └ <function import_module at 0x0000016CDB45D820>
    └ <module 'importlib' from 'C:\\Users\\79892\\AppData\\Local\\Programs\\Python\\Python39\\lib\\importlib\\__init__.py'>

  File "C:\Users\79892\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.StarRailUID.StarRailUID.starrailuid_charinfo'
           │          └ <function _gcd_import at 0x0000016CD9191310>
           └ <module 'importlib._bootstrap' (frozen)>

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "G:\bot\HoshinoBot v2\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py", line 10, in <module>
    from starrail_damage_cal.map.SR_MAP_PATH import avatarId2Name

ModuleNotFoundError: No module named 'starrail_damage_cal'
  File "G:\bot\HoshinoBot v2\gsuid_core\gsuid_core\server.py", line 103, in load_plugins
    self.load_dir_plugins(path, True)
  File "G:\bot\HoshinoBot v2\gsuid_core\gsuid_core\server.py", line 147, in load_dir_plugins
    importlib.import_module(f'{_p}')
  File "C:\Users\79892\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "G:\bot\HoshinoBot v2\gsuid_core\gsuid_core\plugins\StarRailUID\StarRailUID\starrailuid_charinfo\__init__.py", line 10, in <module>
    from starrail_damage_cal.map.SR_MAP_PATH import avatarId2Name
04-21 14:55:22 [WARNING] gsuid_core.server | 插件StarRailUID加载失败
```
尝试`pdm run python -m pip install starrail-damage-cal --upgrade`后仍为加载失败

**Comment by baiqwerdvd** [comment]
在core的目录下执行`pdm run python -m pip install starrail-damage-cal --upgrade`

**Comment by 54yq** [comment]
ok了，感谢
